// StyleCue style personality catalogue — 16 categories.
// Originally 5 (Classic, Edgy, Minimalist, Romantic, Bohemian) per the
// research report; expanded here per the study's revised scope.
// Each style carries attribute tags for the tag-overlap recommendation
// engine, plus richer profile content (tagline, key pieces, styling tips,
// what to avoid, best-for occasions) and image paths for the reveal page.

export const STYLE_TYPES = {
    classic: {
        name: "Classic",
        tagline: "Timeless over trendy.",
        mood: "Put-together, quietly confident — will still look right in ten years.",
        palette: "Navy, camel, white, black, muted neutrals",
        fabrics: "Crisp cotton, wool, structured knits",
        pieces: "Blazers, button-downs, straight-leg trousers, trench coats",
        keyPieces: ["Tailored blazer", "Crisp white shirt", "Straight-leg trousers", "Trench coat", "Structured leather bag"],
        stylingTips: [
            "Invest in fit over trend — a well-tailored basic outlasts ten trendy pieces.",
            "Keep the palette tight; let cut and fabric quality do the talking.",
            "One quality leather accessory (belt, bag, shoes) elevates the whole outfit.",
        ],
        avoid: ["Head-to-toe logos", "Fast-fashion fabrics that lose shape after one wash"],
        bestFor: "Work, interviews, dinners — anywhere you want to look effortlessly credible.",
        attributes: ["tailored", "structured", "neutral-tone", "button-front", "straight-leg"],
        images: {
            hero: "images/styles/classic/hero.jpg",
            palette: "images/styles/classic/palette.jpg",
            detail: "images/styles/classic/detail.jpg",
        },
    },
    edgy: {
        name: "Edgy",
        tagline: "Dressing to stand apart, not blend in.",
        mood: "Unbothered, a little rebellious.",
        palette: "Black, dark tones, occasional sharp accent",
        fabrics: "Leather, denim, stiffer textiles",
        pieces: "Biker jackets, combat boots, asymmetric hems, hardware details",
        keyPieces: ["Leather or faux-leather jacket", "Black skinny or straight jeans", "Combat or chunky boots", "Statement belt", "Asymmetric-hem top"],
        stylingTips: [
            "Contrast textures — leather with soft knit, denim with silk.",
            "Let one hardware piece (boots, belt, jacket) carry the edge; keep the rest simple.",
            "Black-on-black works if you vary the finish (matte vs sheen).",
        ],
        avoid: ["Pastels in bulk", "Overly matched, coordinated sets — a little clash is the point"],
        bestFor: "Nights out, concerts, anywhere you want a bit of attitude.",
        attributes: ["asymmetric", "leather", "structured-shoulder", "dark-tone", "hardware-detail"],
        images: {
            hero: "images/styles/edgy/hero.jpg",
            palette: "images/styles/edgy/palette.jpg",
            detail: "images/styles/edgy/detail.jpg",
        },
    },
    minimalist: {
        name: "Minimalist",
        tagline: "Every piece earns its place.",
        mood: "Deliberate, restrained.",
        palette: "Monochrome, tonal neutrals, one bold color used sparingly",
        fabrics: "Clean-drape, technical fabrics",
        pieces: "Straight trousers, simple tees, unstructured coats, capsule basics",
        keyPieces: ["Plain tee in a quality fabric", "Straight-leg trouser", "Unstructured long coat", "Clean white sneaker", "One statement-free bag"],
        stylingTips: [
            "Build a tight color story (2–3 tones max) so pieces mix freely.",
            "Let silhouette and fabric quality do the work instead of print or logo.",
            "Buy fewer, better pieces — this style rewards a small, well-chosen wardrobe.",
        ],
        avoid: ["Busy prints", "Excess layering or accessories that compete for attention"],
        bestFor: "Work, travel, everyday — built for repeat-wearability.",
        attributes: ["clean-line", "monochrome", "unembellished", "straight-cut", "capsule-basic"],
        images: {
            hero: "images/styles/minimalist/hero.jpg",
            palette: "images/styles/minimalist/palette.jpg",
            detail: "images/styles/minimalist/detail.jpg",
        },
    },
    romantic: {
        name: "Romantic",
        tagline: "Dreamy, gentle, a little nostalgic.",
        mood: "Soft and feminine, drawn to detail.",
        palette: "Pastels, blush tones, florals",
        fabrics: "Chiffon, lace, silk",
        pieces: "Ruffles, wrap dresses, puff sleeves, delicate necklines",
        keyPieces: ["Wrap dress", "Ruffle-sleeve blouse", "Lace-trim slip", "Floral midi skirt", "Delicate layered jewelry"],
        stylingTips: [
            "Let one romantic detail (ruffle, lace, puff sleeve) lead — too many competes.",
            "Balance soft silhouettes with a structured shoe or bag so it doesn't read costume-y.",
            "Soft, muted florals read more elevated than bright, busy ones.",
        ],
        avoid: ["Head-to-toe ruffle or lace at once", "Stiff, structured fabrics that fight the softness"],
        bestFor: "Dates, garden parties, daytime events with a feminine dress code.",
        attributes: ["soft-fabric", "ruffle", "flowy", "v-neck", "lace"],
        images: {
            hero: "images/styles/romantic/hero.jpg",
            palette: "images/styles/romantic/palette.jpg",
            detail: "images/styles/romantic/detail.jpg",
        },
    },
    bohemian: {
        name: "Bohemian",
        tagline: "Unhurried, free-spirited, well-travelled.",
        mood: "Mixing textures without overthinking it.",
        palette: "Earth tones, rust, terracotta, warm prints",
        fabrics: "Crochet, suede, natural/textured fibers",
        pieces: "Maxi skirts, fringe, layered jewelry, wide-leg bottoms",
        keyPieces: ["Flowy maxi skirt", "Suede or fringe jacket", "Crochet top", "Layered necklaces", "Wide-leg trousers"],
        stylingTips: [
            "Layer textures freely — crochet, suede, and print can coexist.",
            "Anchor loose silhouettes with one fitted piece so proportions stay balanced.",
            "Warm, earthy tones tie mismatched prints together.",
        ],
        avoid: ["Overly structured tailoring", "Cool, stark color palettes that fight the earthy mood"],
        bestFor: "Festivals, travel, relaxed weekend gatherings.",
        attributes: ["flowy", "layered", "printed", "wide-leg", "fringe"],
        images: {
            hero: "images/styles/bohemian/hero.jpg",
            palette: "images/styles/bohemian/palette.jpg",
            detail: "images/styles/bohemian/detail.jpg",
        },
    },
    preppy: {
        name: "Preppy",
        tagline: "Wholesome, sporty-smart, collegiate.",
        mood: "Polished with a playful edge.",
        palette: "Navy, kelly green, red, white",
        fabrics: "Cotton, pique knit, tweed",
        pieces: "Polos, blazers, plaid skirts, loafers",
        keyPieces: ["Polo shirt", "Pleated skirt or chino", "Cable-knit sweater", "Penny loafers", "Blazer with a crest or pin"],
        stylingTips: [
            "Stripes, plaid, and solids can mix if the palette stays coordinated.",
            "Layer a sweater over a collared shirt for the classic preppy silhouette.",
            "Loafers or boat shoes finish the look more than sneakers do.",
        ],
        avoid: ["Distressed or grunge-style denim", "All-black outfits — preppy leans bright and clean"],
        bestFor: "Campus, brunch, smart-casual daytime settings.",
        attributes: ["collegiate", "plaid", "polo-collar", "loafer-style", "pique-knit"],
        images: {
            hero: "images/styles/preppy/hero.jpg",
            palette: "images/styles/preppy/palette.jpg",
            detail: "images/styles/preppy/detail.jpg",
        },
    },
    glam: {
        name: "Glam",
        tagline: "Bold, dressed to impress.",
        mood: "Statement-making, unapologetic.",
        palette: "Metallics, jewel tones, black",
        fabrics: "Sequin, satin, velvet",
        pieces: "Bodycon dresses, heels, statement jewelry",
        keyPieces: ["Sequin or satin dress", "Statement heels", "Bold jewelry set", "Structured clutch", "Faux fur or velvet coat"],
        stylingTips: [
            "Pick one focal point — dress or jewelry — and let the rest support it.",
            "Metallics pair well with black for an easy high-contrast base.",
            "Fit matters more here than anywhere else — bodycon pieces need to actually fit.",
        ],
        avoid: ["Under-dressing the occasion", "Mixing too many competing metallics at once"],
        bestFor: "Parties, formal events, anywhere you want to be the best-dressed.",
        attributes: ["sequin", "bodycon", "metallic", "statement-jewelry", "satin"],
        images: {
            hero: "images/styles/glam/hero.jpg",
            palette: "images/styles/glam/palette.jpg",
            detail: "images/styles/glam/detail.jpg",
        },
    },
    streetwear: {
        name: "Streetwear",
        tagline: "Relaxed, culture-driven, casual-urban.",
        mood: "Confident in comfort.",
        palette: "Black, white, graphic",
        fabrics: "Jersey, denim, technical fabrics",
        pieces: "Oversized hoodies, sneakers, cargo pants",
        keyPieces: ["Oversized hoodie", "Cargo pants", "Statement sneakers", "Graphic tee", "Logo cap or beanie"],
        stylingTips: [
            "Oversized on top, fitted on bottom (or vice versa) keeps proportion in check.",
            "Let sneakers be the hero piece — build the outfit around them.",
            "One graphic or logo moment is enough; two competes.",
        ],
        avoid: ["Fully fitted, tailored silhouettes throughout", "Delicate fabrics like silk or lace"],
        bestFor: "Casual hangouts, city days, anywhere comfort matters.",
        attributes: ["oversized", "graphic-print", "sneaker-style", "cargo", "hoodie"],
        images: {
            hero: "images/styles/streetwear/hero.jpg",
            palette: "images/styles/streetwear/palette.jpg",
            detail: "images/styles/streetwear/detail.jpg",
        },
    },
    grunge: {
        name: "Grunge",
        tagline: "Unpolished on purpose, nostalgic for the 90s.",
        mood: "Deliberately undone.",
        palette: "Muted, faded, plaid",
        fabrics: "Distressed denim, flannel",
        pieces: "Flannel shirts, ripped jeans, combat boots",
        keyPieces: ["Oversized flannel shirt", "Ripped or distressed jeans", "Combat boots", "Faded band tee", "Slouchy beanie"],
        stylingTips: [
            "Layer flannel over a plain tee, tied at the waist, for the classic silhouette.",
            "Let denim show visible wear — this style isn't meant to look new.",
            "Keep footwear heavy and worn-in; anything too clean breaks the mood.",
        ],
        avoid: ["Crisp, pressed fabrics", "Polished accessories like fine jewelry"],
        bestFor: "Casual days, gigs, anywhere low-key and unbothered fits.",
        attributes: ["distressed", "flannel", "layered", "combat-boot-style", "faded-tone"],
        images: {
            hero: "images/styles/grunge/hero.jpg",
            palette: "images/styles/grunge/palette.jpg",
            detail: "images/styles/grunge/detail.jpg",
        },
    },
    artsy: {
        name: "Artsy / Eclectic",
        tagline: "Expressive, playful, non-conforming.",
        mood: "Rules are optional.",
        palette: "Unexpected color and pattern combinations",
        fabrics: "Mixed textures",
        pieces: "Statement prints, unconventional silhouettes, mismatched layering",
        keyPieces: ["Statement-print piece", "Unconventional silhouette (asymmetric, oversized, sculptural)", "Mismatched layered pieces", "Handmade or one-off accessory", "Bold color-block item"],
        stylingTips: [
            "Trust unexpected pairings — this style thrives on personal logic, not rules.",
            "One statement print is a focal point; two or three becomes the whole outfit's story.",
            "Vintage and handmade pieces fit naturally here.",
        ],
        avoid: ["Playing it too safe", "Matching everything too neatly — a bit of clash is the point"],
        bestFor: "Gallery openings, creative events, anywhere self-expression is welcome.",
        attributes: ["mixed-print", "unconventional-cut", "color-block", "textural-mix", "statement-print"],
        images: {
            hero: "images/styles/artsy/hero.jpg",
            palette: "images/styles/artsy/palette.jpg",
            detail: "images/styles/artsy/detail.jpg",
        },
    },
    sporty: {
        name: "Sporty / Athleisure",
        tagline: "Active, easy, functional.",
        mood: "Built to move.",
        palette: "Bold brights or monochrome sport tones",
        fabrics: "Technical, stretch fabrics",
        pieces: "Leggings, sneakers, track jackets",
        keyPieces: ["Leggings or joggers", "Performance sneakers", "Zip-up track jacket", "Sports bra or fitted tank", "Crossbody or backpack"],
        stylingTips: [
            "Match your set (top and bottom) for an intentional, put-together sporty look.",
            "One bright color-block moment keeps monochrome sets from feeling flat.",
            "Clean, well-kept sneakers matter — this style lives or dies on footwear condition.",
        ],
        avoid: ["Delicate fabrics that don't move with you", "Overly dressy accessories"],
        bestFor: "Workouts, errands, travel days — anywhere function comes first.",
        attributes: ["stretch-fabric", "track-style", "sneaker-style", "performance-fabric", "zip-front"],
        images: {
            hero: "images/styles/sporty/hero.jpg",
            palette: "images/styles/sporty/palette.jpg",
            detail: "images/styles/sporty/detail.jpg",
        },
    },
    vintage: {
        name: "Vintage / Retro",
        tagline: "Nostalgic, curated, one foot in the past.",
        mood: "Character over trend.",
        palette: "Era-appropriate — 60s brights, 70s earth tones",
        fabrics: "Period-appropriate fabrics",
        pieces: "High-waisted cuts, tea-length skirts, retro prints",
        keyPieces: ["High-waisted trousers or skirt", "Tea-length dress", "Retro-print blouse", "Cat-eye sunglasses", "Structured vintage-style handbag"],
        stylingTips: [
            "Pick one decade to anchor the outfit rather than mixing eras at random.",
            "Thrifted or secondhand pieces add authenticity this style leans on.",
            "Retro prints work best against one solid, era-appropriate color.",
        ],
        avoid: ["Modern technical fabrics that break the period feel", "Mixing too many eras in one outfit"],
        bestFor: "Anywhere you want personality and story over trend-chasing.",
        attributes: ["high-waisted", "retro-print", "tea-length", "era-silhouette", "thrifted-look"],
        images: {
            hero: "images/styles/vintage/hero.jpg",
            palette: "images/styles/vintage/palette.jpg",
            detail: "images/styles/vintage/detail.jpg",
        },
    },
    parisian: {
        name: "Parisian Chic",
        tagline: "Effortless, quietly confident.",
        mood: "Looks unplanned but never is.",
        palette: "Tonal neutrals — black, white, beige",
        fabrics: "Silk, wool, quality basics",
        pieces: "Trench coats, striped tops, tailored trousers",
        keyPieces: ["Trench coat", "Breton striped top", "Tailored trousers", "Silk scarf", "Ballet flats"],
        stylingTips: [
            "Fewer, higher-quality pieces worn on repeat is the whole philosophy here.",
            "A silk scarf, tied simply, is the signature finishing touch.",
            "Keep makeup and styling minimal — this look is about restraint, not more.",
        ],
        avoid: ["Head-to-toe trends", "Overly styled, 'trying too hard' finishes"],
        bestFor: "Everyday wear that still looks intentional — work, errands, dinner.",
        attributes: ["tonal-neutral", "trench", "striped", "tailored", "effortless-drape"],
        images: {
            hero: "images/styles/parisian/hero.jpg",
            palette: "images/styles/parisian/palette.jpg",
            detail: "images/styles/parisian/detail.jpg",
        },
    },
    punk: {
        name: "Punk / Gothic",
        tagline: "Rebellious, dramatic, DIY at heart.",
        mood: "Rules are the first thing to break.",
        palette: "Black, deep red",
        fabrics: "Leather, fishnet, heavy hardware",
        pieces: "Studded jackets, platform boots",
        keyPieces: ["Studded leather jacket", "Platform boots", "Fishnet layering piece", "Tartan bottom", "Chain or spike accessory"],
        stylingTips: [
            "Hardware (studs, chains, spikes) is the signature — one strong piece is enough.",
            "Layer fishnet under ripped or cut fabric for texture depth.",
            "Dark, dramatic makeup often finishes this look as much as the clothing does.",
        ],
        avoid: ["Soft pastels", "Anything that reads 'polished' — the DIY edge is the point"],
        bestFor: "Concerts, nights out, anywhere you want maximum attitude.",
        attributes: ["studded", "platform-boot-style", "fishnet", "dark-tone", "DIY-edge"],
        images: {
            hero: "images/styles/punk/hero.jpg",
            palette: "images/styles/punk/palette.jpg",
            detail: "images/styles/punk/detail.jpg",
        },
    },
    coastal: {
        name: "Coastal / Resort",
        tagline: "Relaxed, sun-drenched, dressed for somewhere warmer.",
        mood: "Breezy and unhurried.",
        palette: "Whites, sun-bleached pastels",
        fabrics: "Linen, cotton voile",
        pieces: "Linen sets, sandals, straw accessories",
        keyPieces: ["Linen shirt or set", "Flowy sundress", "Woven sandals", "Straw bag or hat", "Lightweight kaftan"],
        stylingTips: [
            "Let fabric breathe — this style is built for movement and heat.",
            "Natural textures (straw, woven, linen) do more work here than prints.",
            "Sun-faded, slightly imperfect tones read more authentic than bright brand-new pastels.",
        ],
        avoid: ["Heavy, structured fabrics", "Dark, saturated palettes"],
        bestFor: "Beach days, resort travel, warm-weather everything.",
        attributes: ["linen", "breezy", "sun-faded", "resort-cut", "straw-texture"],
        images: {
            hero: "images/styles/coastal/hero.jpg",
            palette: "images/styles/coastal/palette.jpg",
            detail: "images/styles/coastal/detail.jpg",
        },
    },
    cottagecore: {
        name: "Cottagecore",
        tagline: "Whimsical, nostalgic for simpler things.",
        mood: "Prairie-soft and unhurried.",
        palette: "Soft florals, muted pastels",
        fabrics: "Cotton, gingham, lace trim",
        pieces: "Puff sleeves, prairie dresses, floral prints",
        keyPieces: ["Puff-sleeve prairie dress", "Gingham top", "Floral midi skirt", "Knit cardigan", "Woven basket bag"],
        stylingTips: [
            "Small ditsy florals read softer and more cottagecore than large bold ones.",
            "Layer a cardigan over a dress for the quintessential prairie silhouette.",
            "Natural, slightly undone hair and minimal makeup complete the mood.",
        ],
        avoid: ["Sharp, structured tailoring", "Metallics or high-shine fabrics"],
        bestFor: "Picnics, garden visits, anywhere soft and unhurried fits.",
        attributes: ["prairie-cut", "gingham", "puff-sleeve", "floral-print", "lace-trim"],
        images: {
            hero: "images/styles/cottagecore/hero.jpg",
            palette: "images/styles/cottagecore/palette.jpg",
            detail: "images/styles/cottagecore/detail.jpg",
        },
    },
};